name: qmdock
channels:
  - conda-forge
dependencies:
  - python=3.12
  - libblas=*=*openblas
  - numpy
  - scipy
  - pandas
  - rdkit
  - pytest
  - pip
  - pip:
      - tblite
      - tqdm
      - dimorphite-dl
      - torch
